// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_fhqPKTC1oiUtaa8lAUOJxzpixlVq8rI',
    appId: '1:843646058643:web:a411d83fb118fc0ba10d66',
    messagingSenderId: '843646058643',
    projectId: 'notification-47e11',
    authDomain: 'notification-47e11.firebaseapp.com',
    storageBucket: 'notification-47e11.firebasestorage.app',
    measurementId: 'G-SNVWRQ3H1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnbjzpEXXWqFIywKf_fyWRT_nrbRQkoe0',
    appId: '1:843646058643:android:940082a62f36eed8a10d66',
    messagingSenderId: '843646058643',
    projectId: 'notification-47e11',
    storageBucket: 'notification-47e11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxkCqjaSELJUFw_aL2_SSUj8U257qCIEc',
    appId: '1:843646058643:ios:fe74cfd072dbff22a10d66',
    messagingSenderId: '843646058643',
    projectId: 'notification-47e11',
    storageBucket: 'notification-47e11.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxkCqjaSELJUFw_aL2_SSUj8U257qCIEc',
    appId: '1:843646058643:ios:fe74cfd072dbff22a10d66',
    messagingSenderId: '843646058643',
    projectId: 'notification-47e11',
    storageBucket: 'notification-47e11.firebasestorage.app',
    iosBundleId: 'com.example.notification',
  );

}