
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';

class DashboardPdfUtils {
  static Future<void> generateAndDownloadDashboardSummary({
    required String shopName,
    required Map<String, dynamic> dashboardData,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final dateFormat = DateFormat('MMM dd, yyyy - hh:mm a');
    final currencyFormat = NumberFormat.currency(symbol: 'Rs. ', decimalDigits: 2);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'DASHBOARD SUMMARY',
                        style: pw.TextStyle(
                          fontSize: 24,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColor.fromInt(0xFF2563EB),
                        ),
                      ),
                      pw.SizedBox(height: 4),
                      pw.Text(shopName, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14)),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Snapshot Date:', style: const pw.TextStyle(fontSize: 10)),
                      pw.Text(dateFormat.format(now), style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11)),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 32),
              pw.Divider(thickness: 1, color: PdfColors.grey300),
              pw.SizedBox(height: 32),

              // Summary Grid (Stats)
              pw.Wrap(
                spacing: 20,
                runSpacing: 20,
                children: [
                  _buildStatBox("Today's Sales", currencyFormat.format(dashboardData['todaysSales'] ?? 0.0), PdfColors.green700),
                  _buildStatBox("Low Stock Items", "${dashboardData['lowStockCount'] ?? 0} Items", PdfColors.red700),
                  _buildStatBox("Customer Credit", currencyFormat.format(dashboardData['customerCredit'] ?? 0.0), PdfColors.orange700),
                  _buildStatBox("To Suppliers", currencyFormat.format(dashboardData['toSuppliers'] ?? 0.0), PdfColors.blue700),
                ],
              ),

              pw.SizedBox(height: 48),
              pw.Text('RECENT TRANSACTIONS', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: PdfColors.grey700)),
              pw.SizedBox(height: 12),
              
              // Recent Transactions Table
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey200, width: 0.5),
                columnWidths: {
                  0: const pw.FlexColumnWidth(2),
                  1: const pw.FlexColumnWidth(4),
                  2: const pw.FlexColumnWidth(2),
                },
                children: [
                   pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                    children: [
                      _buildCell('Time', isHeader: true),
                      _buildCell('Description', isHeader: true),
                      _buildCell('Amount', isHeader: true),
                    ],
                  ),
                  ... (dashboardData['recentTransactions'] as List? ?? []).map((txn) {
                    return pw.TableRow(
                      children: [
                        _buildCell(txn['time'] ?? ''),
                        _buildCell("${txn['title']}\n${txn['subtitle']}"),
                        _buildCell(
                          'Rs. ${(txn['amount'] ?? 0.0).toStringAsFixed(0)}',
                          align: pw.TextAlign.right,
                        ),
                      ],
                    );
                  }),
                ],
              ),

              pw.Spacer(),
              pw.Divider(thickness: 0.5, color: PdfColors.grey300),
              pw.SizedBox(height: 8),
              pw.Center(
                child: pw.Text(
                  'Generated by ClickBuy - Premium Business Intelligence',
                  style: pw.TextStyle(fontSize: 9, fontStyle: pw.FontStyle.italic, color: PdfColors.grey600),
                ),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Dashboard_Summary_${DateFormat('yyyyMMdd').format(now)}.pdf',
    );
  }

  static pw.Widget _buildStatBox(String label, String value, PdfColor color) {
    return pw.Container(
      width: 150,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey200),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
          pw.SizedBox(height: 4),
          pw.Text(value, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: color)),
        ],
      ),
    );
  }

  static pw.Padding _buildCell(String text, {bool isHeader = false, pw.TextAlign align = pw.TextAlign.left}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
          fontSize: isHeader ? 10 : 9,
        ),
        textAlign: align,
      ),
    );
  }
}
